telegram:
  userName: ${TELEGRAM_USERNAME}
  token: ${TELEGRAM_TOKEN}
  chatId: ${TELEGRAM_CHATID}
  userId: ${TELEGRAM_USERID}
  parseMode: HTML

selenium:
  headless:
    mode: true

schedule:
  pepper:
    init: PT10S
    work: PT10S

spring:
  data:
    redis:
      host: ${REDIS_IP}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}